package com.aim.questionnaire.dao;

import com.aim.questionnaire.dao.entity.ModelEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ModelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    int insert(ModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    int insertSelective(ModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    ModelEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ModelEntity record);

    /**
     * 添加模块信息
     * @param map
     * @return
     */
    int addModelInfo(Map<String, Object> map);

    /**
     * 修改模块信息
     * @param map
     * @return
     */
    int modifyModelInfo(Map<String, Object> map);

    /**
     * 删除模块信息
     * @param map
     * @return
     */
    int deleteModelInfo(Map<String, Object> map);

    /**
     * 查询模块信息列表
     * @param map
     * @return
     */
    List<Map<String, Object>> queryModelListInfo(Map<String, Object> map);

    /**
     * 查询是否存在此排序
     * @param sort
     * @param parentId
     * @return
     */
    int queryModelSortIsExist(@Param("sort") String sort,@Param("parentId") String parentId);

    /**
     * 查询parentId对应的status，用于匹配role的list
     * @return
     */
    List<Map<String, Object>> queryModelStatusNum();

    /**
     * 查询模块信息
     * @param strResult
     * @return
     */
    List<Map<String, Object>> queryModelListByStatus(List<String> strResult);

    /**
     * 查询模块路径根据id
     * @param strList
     * @return
     */
    List<Map<String, Object>> queryModelPathById(@Param("strList") List<String> strList);

    /**
     * 查询最大的id值
     * @return
     */
    int queryModelMaxId();

    /**
     * 查询此状态下的个数
     * @param status
     * @return
     */
    int queryModelStatusCountByStatus(@Param("status") String status);
    /**
     * 查询模块名字重复
     * @param map
     * @return
     */
    List<ModelEntity> queryModeNameInfo(Map<String, Object> map);
}