package com.aim.questionnaire.dao.entity;

public class ModelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.model_name
     *
     * @mbg.generated
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.one_model
     *
     * @mbg.generated
     */
    private String oneModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.two_model
     *
     * @mbg.generated
     */
    private String twoModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.id
     *
     * @return the value of model_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.id
     *
     * @param id the value for model_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.parent_id
     *
     * @return the value of model_info.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.parent_id
     *
     * @param parentId the value for model_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.model_name
     *
     * @return the value of model_info.model_name
     *
     * @mbg.generated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.model_name
     *
     * @param modelName the value for model_info.model_name
     *
     * @mbg.generated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.one_model
     *
     * @return the value of model_info.one_model
     *
     * @mbg.generated
     */
    public String getOneModel() {
        return oneModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.one_model
     *
     * @param oneModel the value for model_info.one_model
     *
     * @mbg.generated
     */
    public void setOneModel(String oneModel) {
        this.oneModel = oneModel == null ? null : oneModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.two_model
     *
     * @return the value of model_info.two_model
     *
     * @mbg.generated
     */
    public String getTwoModel() {
        return twoModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.two_model
     *
     * @param twoModel the value for model_info.two_model
     *
     * @mbg.generated
     */
    public void setTwoModel(String twoModel) {
        this.twoModel = twoModel == null ? null : twoModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.path
     *
     * @return the value of model_info.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.path
     *
     * @param path the value for model_info.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.sort
     *
     * @return the value of model_info.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.sort
     *
     * @param sort the value for model_info.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.created_by
     *
     * @return the value of model_info.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.created_by
     *
     * @param createdBy the value for model_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_info.status
     *
     * @return the value of model_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_info.status
     *
     * @param status the value for model_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}