package com.aim.questionnaire.dao.entity;

import java.util.Date;

public class ParameterConfigEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.property
     *
     * @mbg.generated
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.describ
     *
     * @mbg.generated
     */
    private String describ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.creation_date
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.last_updated_by
     *
     * @mbg.generated
     */
    private String lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter_config_info.last_update_date
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.id
     *
     * @return the value of parameter_config_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.id
     *
     * @param id the value for parameter_config_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.property
     *
     * @return the value of parameter_config_info.property
     *
     * @mbg.generated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.property
     *
     * @param property the value for parameter_config_info.property
     *
     * @mbg.generated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.data
     *
     * @return the value of parameter_config_info.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.data
     *
     * @param data the value for parameter_config_info.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.describ
     *
     * @return the value of parameter_config_info.describ
     *
     * @mbg.generated
     */
    public String getDescrib() {
        return describ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.describ
     *
     * @param describ the value for parameter_config_info.describ
     *
     * @mbg.generated
     */
    public void setDescrib(String describ) {
        this.describ = describ == null ? null : describ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.created_by
     *
     * @return the value of parameter_config_info.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.created_by
     *
     * @param createdBy the value for parameter_config_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.creation_date
     *
     * @return the value of parameter_config_info.creation_date
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.creation_date
     *
     * @param creationDate the value for parameter_config_info.creation_date
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.last_updated_by
     *
     * @return the value of parameter_config_info.last_updated_by
     *
     * @mbg.generated
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.last_updated_by
     *
     * @param lastUpdatedBy the value for parameter_config_info.last_updated_by
     *
     * @mbg.generated
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter_config_info.last_update_date
     *
     * @return the value of parameter_config_info.last_update_date
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter_config_info.last_update_date
     *
     * @param lastUpdateDate the value for parameter_config_info.last_update_date
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}